version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: boardgame_tracker_db
    environment:
      POSTGRES_DB: boardgame_tracker
      POSTGRES_USER: boardgame_user
      POSTGRES_PASSWORD: boardgame_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
